language: go
dist: xenial
sudo: true
services:
  - docker
env:
  matrix:
    - GO111MODULE=on
matrix:
  include:
    - os: linux
      go: 1.13.x
      cache:
        directories:
          - "/home/travis/.cache/go-build" # GOCACHE
    - os: osx
      go: 1.13.x
      cache:
        directories:
          - "/Users/travis/Library/Caches/go-build" # GOCACHE
before_install:
  # Setup directory for binaries
  - mkdir ./bin
  - export PATH=$PATH:$PWD/bin
  # Misspell
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O misspell.tar.gz https://github.com/client9/misspell/releases/download/v0.3.4/misspell_0.3.4_linux_64bit.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -O misspell.tar.gz https://github.com/client9/misspell/releases/download/v0.3.4/misspell_0.3.4_mac_64bit.tar.gz; fi
  - tar xf misspell.tar.gz && cp ./misspell ./bin/misspell
  # staticcheck
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O staticcheck.tar.gz https://github.com/dominikh/go-tools/releases/download/2019.2.3/staticcheck_linux_amd64.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -O staticcheck.tar.gz https://github.com/dominikh/go-tools/releases/download/2019.2.3/staticcheck_darwin_amd64.tar.gz; fi
  - tar xf staticcheck.tar.gz && cp ./staticcheck/staticcheck ./bin/staticcheck
  # nancy (vulnerable dependencies)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L -o ./bin/nancy https://github.com/sonatype-nexus-community/nancy/releases/download/v0.1.0/nancy-linux.amd64-v0.1.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L -o ./bin/nancy https://github.com/sonatype-nexus-community/nancy/releases/download/v0.1.0/nancy-darwin.amd64-v0.1.0; fi
  - chmod +x ./bin/nancy
  # golangci-lint
  - wget -O - -q https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.23.6
  # gocyclo
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O ./bin/gocyclo https://github.com/adamdecaf/gocyclo/releases/download/2019-08-09/gocyclo-linux-amd64; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -O ./bin/gocyclo https://github.com/adamdecaf/gocyclo/releases/download/2019-08-09/gocyclo-darwin-amd64; fi
  - chmod +x ./bin/gocyclo
  # apitest
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O ./bin/apitest https://github.com/moov-io/api/releases/download/v2019.11.01.1/apitest-linux-amd64; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -O ./bin/apitest https://github.com/moov-io/api/releases/download/v2019.11.01.1/apitest-darwin-amd64; fi
  - chmod +x ./bin/apitest
  # - go get github.com/moov-io/api/cmd/apitest@master
before_script:
  - GOFILES=$(find . -type f -name '*.go' | grep -v client | grep -v vendor)
  - go mod graph
script:
  # Just check gofmt on linux, it's the fastest builder
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -z $(gofmt -s -l $GOFILES); fi
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - misspell -error -locale US $GOFILES
  - gocyclo -over 25 $GOFILES
  - go list -m all | ./bin/nancy -exclude-vulnerability CVE-2020-7220,2b1dc3ea-0783-4eaa-a678-236cf05953db # Vault Enterprise, needs gocloud.dev release
  - ./bin/golangci-lint run --skip-dirs="(admin|client)" --timeout=2m --disable=errcheck
  - staticcheck ./cmd/server/*.go ./internal/*/*.go ./pkg/*/*.go *.go
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make docker && make test-integration; fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make docker
after_script:
  - docker-compose logs
  - make clean-integration
before_deploy:
  - make dist
deploy:
  provider: releases
  api_key:
    secure: JaZPNf9Er+wCWwqgfGQowRL8/FZ8FZ4I1CI65ZI16j0HuSxUSdl4ygOeF8SNZ3UMecC8OlRhyuyxIEfoFpxjKvKL7fNyCJCfDGIY/icqmbNoTZitaJwF2QkYQ97U8gtAi1951kcI5A118Ynd/6jKCyYjEhhnlVMJwVuk723A0qWgRFzVekoMWuc+wo4diCrAjVXKvwivJn2CpAYkMlTpQTZgAQm4XbnHtnoB/sR7uDmJpeiOjShfFtYfOTsrqINJND+3bdPTySkPO4MaZ8yB+esdF69URSWOsGhdJf7O0m+494mQjeMdmqyAj0XD7D6NW0253N7oh2ikSa1Cq0xJ1zvUFMnvu3DVlQkEmF+G9pB+C+x0lbxmhO4UelX9wETnohRjZvxqQACZhZrTsh4B+AdGKM1kZkBXpm38aT0U80w7ICczg952is04ZX1YBXXl4m3tWd6MlN3hEdzDaPMj57Rg9v+SyslCLYPQfi0uP1fSc/gjYHogY8UvSLI8R+H7ri71pe/ACoJ/tew6Z6oKyHAigivTBXcGWcDOSWP2DfLBdSrqsKtnDJPiieyINsqzTY1xsHggSTj7bW4PGetg7Yudmf1LB4/A5W5cOTSdhMB4NZh14dbASL/l7eHeZhXGng3XWLX1dBu3h4dsTIm+Mnj/YCbYXFprk4IHzLjADYM=
  file_glob: true
  file:
    - bin/paygate-*
  on:
    repo: moov-io/paygate
    tags: true
    go: 1.13.x
  skip_cleanup: true
after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release-push
notifications:
  slack:
    secure: ZJwRHo5yVXMyJ3p4aTM9dQj3NGnrnUoue2bTdTL5W0pHfy+wmqF/ccbTmZrMdNRSaofmLjQ1MS2hnAj3COYZJt+EN3VKG9WCJ8Pcvr6kl6Lmne2f27iGJUTmmQM/ngW4katjTy+BOE3ON5tloa+ixw06jQi/mNLEptj8He49QQDvbTkfP9xrNwMVXqyAEz8AooYHhT3HNc9YpNXnaH703XhHa19R5Kpdolkg5wgVoAGCYJ6PgBBSRfBvXtCqbThVmsean1yZuaXqxjj8WboQ/yiSt8g4cz0+qVsRWa2nvYn3DgP+0cVK4TXJNJ5ruPPpkjIOBye/Zl2ww2qO9OWQxZ1XiFln4sJH6GpZrgT/DsiUJbqcgmNELhDWSY96vEqrEpGAG3uDiTubqO1G3iRGwep6kcIoTPlCouJBRm5mLhdTk/kQazqxkfLn3bamLw+a5rN3UHYeq3s0VAxzDhmziZFBAQCH3OF2+Se7mjyW9w4t7opMF5texXknbluzJR0OVHjjIxj+po4aIpuS6wpQ97jtg3PbQnTE8ogxW8JdTlpG1PVuWh3HwzyMa33qILyx0AFgV9z668O9u0HiF2Xosjx7gBl/bvVJP3XMCZFtc3NHT8Ahz7UOoq7vlI1zumo1KkdPdioJvcfDg121u21/6pohuI1tKzNrVvesppDnN9Y=
