language: go
dist: xenial
sudo: true
services:
  - docker
env:
  matrix:
    - GO111MODULE=on
matrix:
  include:
    - os: linux
      go: 1.12.x
      cache:
        directories:
          - "/home/travis/.cache/go-build" # GOCACHE
    - os: osx
      go: 1.12.x
      cache:
        directories:
          - "/Users/travis/Library/Caches/go-build" # GOCACHE
before_install:
  - go get -u github.com/client9/misspell/cmd/misspell
  - go get -u golang.org/x/lint/golint
  - go get github.com/fzipp/gocyclo
  - go get -u honnef.co/go/tools/cmd/staticcheck
  - go get golang.org/x/tools/cmd/cover
before_script:
  - GOFILES=$(find . -type f -name '*.go' | grep -v vendor)
script:
  # Just check gofmt on linux, it's the fastest builder
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -z $(gofmt -s -l $GOFILES); fi
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - misspell -error -locale US $GOFILES
  - gocyclo -over 25 $GOFILES
  - golint -set_exit_status $GOFILES
  - staticcheck ./pkg/*/*.go *.go # TODO(adam): move main.go and check ./cmd/*/*.go
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make docker
before_deploy:
  - make dist
deploy:
  provider: releases
  api_key:
    secure: JaZPNf9Er+wCWwqgfGQowRL8/FZ8FZ4I1CI65ZI16j0HuSxUSdl4ygOeF8SNZ3UMecC8OlRhyuyxIEfoFpxjKvKL7fNyCJCfDGIY/icqmbNoTZitaJwF2QkYQ97U8gtAi1951kcI5A118Ynd/6jKCyYjEhhnlVMJwVuk723A0qWgRFzVekoMWuc+wo4diCrAjVXKvwivJn2CpAYkMlTpQTZgAQm4XbnHtnoB/sR7uDmJpeiOjShfFtYfOTsrqINJND+3bdPTySkPO4MaZ8yB+esdF69URSWOsGhdJf7O0m+494mQjeMdmqyAj0XD7D6NW0253N7oh2ikSa1Cq0xJ1zvUFMnvu3DVlQkEmF+G9pB+C+x0lbxmhO4UelX9wETnohRjZvxqQACZhZrTsh4B+AdGKM1kZkBXpm38aT0U80w7ICczg952is04ZX1YBXXl4m3tWd6MlN3hEdzDaPMj57Rg9v+SyslCLYPQfi0uP1fSc/gjYHogY8UvSLI8R+H7ri71pe/ACoJ/tew6Z6oKyHAigivTBXcGWcDOSWP2DfLBdSrqsKtnDJPiieyINsqzTY1xsHggSTj7bW4PGetg7Yudmf1LB4/A5W5cOTSdhMB4NZh14dbASL/l7eHeZhXGng3XWLX1dBu3h4dsTIm+Mnj/YCbYXFprk4IHzLjADYM=
  file_glob: true
  file:
    - bin/paygate-*
  on:
    repo: moov-io/paygate
    tags: true
    go: 1.12.x
  skip_cleanup: true
after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release-push
