# In the wild: https://github.com/cloudflare/logshare
# Go on Travis: https://docs.travis-ci.com/user/languages/go/
# GitHub Releases Uploading: https://docs.travis-ci.com/user/deployment/releases/
# Git Basics - Tagging https://git-scm.com/book/en/v2/Git-Basics-Tagging
# git tag -a v0.0.1 -m "Testing Travis-CI binary release"
# git push origin v0.0.1-pre-release
language: go
sudo: required
services:
    - docker
matrix:
  include:
    - go: 1.x
      env: LATEST=true
  allow_failures:
    - go: tip
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/wadey/gocovmerge
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
  - go get -u honnef.co/go/tools/cmd/megacheck
  - go get -u github.com/client9/misspell/cmd/misspell
before_script:
  - EXCLUDE_VENDOR=$(go list ./... | grep -v "/vendor/")
  - go build
  - $(exit $(go fmt $EXCLUDE_VENDOR | wc -l))
  - go vet $EXCLUDE_VENDOR
  - misspell -error -locale US ./...
  - megacheck $EXCLUDE_VENDOR
script:
  - go test -i -race $EXCLUDE_VENDOR
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
  # Migrate this to a script that only runs on tag'ed releases
  - if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64 386" -output="achsvc.{{.OS}}.{{.Arch}}" -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi
after_success:
  - docker build -t moov/achsvc .
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GITHUB_TOKEN
  file:
    - achsvc.windows.amd64.exe
    - achsvc.windows.386.exe
    - achsvc.darwin.amd64
    - achsvc.linux.amd64
    - achsvc.linux.386
  on:
      repo: moov-io/achsvc
      tags: true
      condition: $LATEST = true
      branch: master
  provider: script
  script: bash .travis-ci/docker_push
  on:
    branch: master
notifications:
    slack: moov-io:v1UY1yfnO8tdNRw1PStyKY5L
