version: '3'
services:
  accounts:
    image: moov/accounts:v0.4.1
    ports:
      - "8085:8085"
      - "9095:9095"
    environment:
      DEFAULT_ROUTING_NUMBER: '121042882'
  auth:
    image: moov/auth:v0.8.0
    ports:
      - "8081:8081"
      - "9091:9091"
  customers:
    image: moov/customers:v0.4.0-rc1
    ports:
      - "8087:8087"
      - "9097:9097"
    environment:
      WATCHMAN_ENDPOINT: 'http://watchman:8084'
    depends_on:
      - watchman
  fed:
    image: moov/fed:v0.4.3
    ports:
      - "8086:8086"
      - "9096:9096"
    environment:
      FEDACH_DATA_PATH: './data/fed/FedACHdir.txt'
      FEDWIRE_DATA_PATH: './data/fed/fpddir.txt'
  watchman:
    image: moov/watchman:static
    ports:
      - "8084:8084"
      - "9094:9094"
  paygate:
    image: moov/paygate:latest
    ports:
      - "8082:8082"
      - "9092:9092"
    command: ["-http.addr", ":8082"]
    environment:
      ACCOUNTS_ENDPOINT: 'http://accounts:8085'
      ACH_ENDPOINT: 'http://ach:8080'
      CUSTOMERS_ENDPOINT: 'http://customers:8087'
      FED_ENDPOINT: 'http://fed:8086'
      ACH_FILE_MAX_LINES: 20 # upload files when they're a lot smaller than the 10k default
      ACH_FILE_TRANSFER_INTERVAL: 30s # Merge and Upload files this often
    depends_on:
      - accounts
      - ach
      - auth
      - customers
      - fed
