logging:
  format: "plain"
customers:
  endpoint: "http://customers:8087"
  accounts:
    decryptor:
      symmetric:
        # INSECURE KEY -- Do not use in production!
        keyURI: 'base64key://MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI='
  debug: true
database:
  sqlite:
    path: "paygate.db"
odfi:
  routingNumber: "221475786"
  gateway:
    # origin is often an ABA routing number
    origin: "221475786"
    # origin_name is the name of your ODFI
    originName: "Teachers FCU"
    # destination can be the ABA routing number of the Federal Reserve bank used
    destination: "071000301"
    # destination_name would be name of Federal Reserve bank used
    destinationName: "FRBATLANTA"
  inboundPath: "./inbound/"
  outboundPath: "./outbound/"
  returnPath: "./returned/"
  cutoffs:
    timezone: "America/New_York"
    windows:
      - "16:20" # 4:20pm EST
  inbound:
    interval: "10m"
  fileConfig:
    batchHeader:
      companyIdentification: "MoovZZZZZZ"
    balanceEntries: true
  ftp:
    hostname: "ftp:2121"
    username: "admin"
    password: "123456"
  # sftp:
  #   hostname: "localhost:2222"
  #   username: "demo"
  #   password: "password"
  storage:
    cleanupLocalDirectory: true
    keepRemoteFiles: false
    local:
      directory: "./storage/"
transfers:
  limits:
    fixed:
      softLimit: 500000  #  $5,000.00
      hardLimit: 1000000 # $10,000.00
validation:
  microDeposits:
    source:
      customerID: "replace-me"
      accountID: "replace-me"
      organization: "replace-me"
pipeline:
  output:
    format: "nacha"
  stream:
    inmem:
      url: 'mem://paygate'
  notifications:
    email:
      from: "noreply@moov.io"
      to:
        - "jane@moov.io"
        - "john@moov.io"
      connectionURI: "smtps://test:test@localhost:1025/?insecure_skip_verify=true"
      companyName: "Moov"
